<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="environment.props" />

    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <RootNamespace>ProceduralRoads</RootNamespace>
        <AssemblyName>ProceduralRoads</AssemblyName>
        <LangVersion>10</LangVersion>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
        <!-- Keep existing AssemblyInfo.cs -->
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <Optimize>false</Optimize>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DebugType>pdbonly</DebugType>
        <Optimize>true</Optimize>
        <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>


    <!-- Additional Content Files to Include in Project -->
    <ItemGroup>
        <None Include="App.config"/>
        <None Include="assets/**" CopyToOutputDirectory="PreserveNewest"/>
        <None Include="icons/**"/>
        <None Include="Thunderstore/**"/>
        <None Include="*.md"/>
        <None Include="*.ps1"/>
    </ItemGroup>

    <!-- Build Targets -->
    <Target Name="ReadPluginAssemblyVersion" AfterTargets="Build">
        <GetAssemblyIdentity AssemblyFiles="$(TargetPath)">
            <Output TaskParameter="Assemblies" ItemName="Targets"/>
        </GetAssemblyIdentity>
        <ItemGroup>
            <AssemblyVersions Include="@(Targets->'%(Version)')"/>
        </ItemGroup>
        <PropertyGroup>
            <AssemblyVersion>%(AssemblyVersions.Identity)</AssemblyVersion>
            <Major>$(AssemblyVersion.Split('.')[0])</Major>
            <Minor>$(AssemblyVersion.Split('.')[1])</Minor>
            <Patch>$(AssemblyVersion.Split('.')[2])</Patch>
            <PackageName>$(AssemblyName)_v$(Major).$(Minor).$(Patch)</PackageName>
            <PackageVersion>$(Major).$(Minor).$(Patch)</PackageVersion>
            <VersionString>$(Major).$(Minor).$(Patch)</VersionString>
            <PackageDir>$(ProjectDir)/Thunderstore/$(PackageName)</PackageDir>
        </PropertyGroup>
    </Target>
    
    <Target Name="CopyOutputDLL" AfterTargets="ReadPluginAssemblyVersion" Condition="Exists('$(CopyOutputDLLPath)')">
        <Error Text="DLL not found in target directory." Condition="!Exists('$(TargetDir)$(AssemblyName).dll')"/>
        <Copy SourceFiles="$(TargetDir)$(AssemblyName).dll" DestinationFolder="$(CopyOutputDLLPath)" OverwriteReadOnlyFiles="true"/>
        <Copy SourceFiles="$(TargetDir)$(AssemblyName).dll" DestinationFolder="$(CopyOutputDLLPath2)" OverwriteReadOnlyFiles="true" Condition="Exists('$(CopyOutputDLLPath2)')"/>
        <Copy SourceFiles="$(TargetDir)$(AssemblyName).dll" DestinationFolder="$(CopyOutputDLLPath3)" OverwriteReadOnlyFiles="true" Condition="Exists('$(CopyOutputDLLPath3)')"/>
    </Target>
    
    <Target Name="MakeThunderstorePackage" AfterTargets="ReadPluginAssemblyVersion" Condition=" '$(Configuration)' == 'Release' ">
        <Error Text="manifest.json not found in Thunderstore directory." Condition="!Exists('$(ProjectDir)/Thunderstore/manifest.json')"/>
        <Error Text="icon.png not found in Thunderstore directory." Condition="!Exists('$(ProjectDir)/Thunderstore/icon.png')"/>
        <Error Text="README.md not found in Thunderstore directory." Condition="!Exists('$(ProjectDir)/Thunderstore/README.md')"/>
        <Error Text="CHANGELOG.md not found in Thunderstore directory." Condition="!Exists('$(ProjectDir)/Thunderstore/CHANGELOG.md')"/>
        <ItemGroup>
            <PackageFiles Include="$(TargetDir)$(AssemblyName).dll"/>
            <PackageFiles Include="$(ProjectDir)/Thunderstore/README.md"/>
            <PackageFiles Include="$(ProjectDir)/Thunderstore/CHANGELOG.md"/>
            <PackageFiles Include="$(ProjectDir)/Thunderstore/manifest.json"/>
            <PackageFiles Include="$(ProjectDir)/Thunderstore/icon.png"/>
        </ItemGroup>
        <MakeDir Directories="$(PackageDir)"/>
        <Copy SourceFiles="@(PackageFiles)" DestinationFolder="$(PackageDir)"/>
        <ZipDirectory SourceDirectory="$(PackageDir)" DestinationFile="$(ProjectDir)/Thunderstore/$(PackageName).zip" Overwrite="true"/>
        <RemoveDir Directories="$(PackageDir)"/>
    </Target>
    
    <Target Name="MakeNexusPackage" AfterTargets="MakeThunderstorePackage" Condition=" '$(Configuration)' == 'Release' ">
        <MakeDir Directories="$(ProjectDir)/Nexus"/>
        <ItemGroup>
            <NexusPackageFiles Include="$(TargetDir)$(AssemblyName).dll;"/>
        </ItemGroup>
        <MakeDir Directories="$(PackageDir)"/>
        <Copy SourceFiles="@(NexusPackageFiles)" DestinationFolder="$(PackageDir)"/>
        <ZipDirectory SourceDirectory="$(PackageDir)" DestinationFile="$(ProjectDir)/Nexus/$(PackageName).zip" Overwrite="true"/>
        <RemoveDir Directories="$(PackageDir)"/>
    </Target>

</Project>
